name       : python-pluggy
version    : 0.11.0
release    : 5
source     :
    - https://github.com/pytest-dev/pluggy/archive/0.11.0.tar.gz : 884269f4ae852112fd74b499876ef2662990db88a21fcb91b579cba3e0467a59
license    : MIT
component  : programming.python
summary    : Plugin management and hook calling for Python
description: |
    Plugin management and hook calling for Python
builddeps  :
    - pytest-runner
    - python-setuptools-scm
environment: |
    export SETUPTOOLS_SCM_PRETEND_VERSION=$version
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
# Uncomment once pytest has been updated to 4.4.x or higher
#check      : |
#    %python_test setup.py pytest
#    %python3_test setup.py pytest
