name       : python-pluggy
version    : 0.13.0
release    : 8
source     :
    - https://github.com/pytest-dev/pluggy/archive/0.13.0.tar.gz : 9d90ecca99633eddfae283eaba39a07b8e3f502515d12cf297fcde3d826cb3f9
license    : MIT
component  : programming.python
summary    : Plugin management and hook calling for Python
description: |
    Plugin management and hook calling for Python
builddeps  :
    - pytest-runner
    - python-importlib-metadata
    - python-setuptools-scm
rundeps    :
    - python-importlib-metadata
environment: |
    export SETUPTOOLS_SCM_PRETEND_VERSION=$version
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test pytest
    %python3_test pytest
