name       : python-pluggy
version    : 0.6.0
release    : 2
source     :
    - https://github.com/pytest-dev/pluggy/archive/0.6.0.tar.gz : 2dcdf93b644ebbd40c1679dec551b289aa502e77100af4153175ada9cac5d4ff
license    : MIT
component  : programming.python
summary    : Plugin management and hook calling for Python
description: |
    Plugin management and hook calling for Python
builddeps  :
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
