name       : python-pluggy
version    : 0.4.0
release    : 1
source     :
    - https://github.com/pytest-dev/pluggy/archive/0.4.0.tar.gz : bc4b259f0b83f034641a74a2237d5fa816cec2423ca795089f57fcbcaca75f37
license    : MIT
component  : programming.python
summary    : Plugin management and hook calling for Python
description: |
    Plugin management and hook calling for Python
builddeps  :
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
