name       : python-pluggy
version    : 1.0.0
release    : 16
source     :
    - https://files.pythonhosted.org/packages/source/p/pluggy/pluggy-1.0.0.tar.gz : 4224373bacce55f955a878bf9cfa763c1e360858e330072059e10bad68531159
homepage   : https://github.com/pytest-dev/pluggy
license    : MIT
component  : programming.python
summary    : Plugin management and hook calling for Python
description: |
    Plugin management and hook calling for Python
builddeps  :
    - python-pytest
    - python-setuptools-scm
environment: |
    export SETUPTOOLS_SCM_PRETEND_VERSION=$version
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
